version: '3'

services:
  # Client App
  insights-app:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npx nx run insights-app:serve --host=0.0.0.0
    ports:
      - ${CLIENT_PORT}:4200
      - 42423:42423
    environment:
      - VITE_BE=${NGINX_DOMAIN}
      - VITE_CLIENT_ID=${CLIENT_ID}

  # Node.js Server App
  node-server:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npx nx run node-server:serve --host=0.0.0.0
    ports:
      - ${SERVER_PORT}:3000
    environment:
      - PORT=3000
      - DB_URI=${DB_URI}
      - REDIRECT_URL=${NGINX_DOMAIN}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}

volumes:
  mono-node-modules: null
