services:
  # Client App
  entry-app:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npx nx run entry-app:serve --host=0.0.0.0
    ports:
      - ${CLIENT_PORT}:4200
      # PORT for million lint
      # - 42423:42423
    environment:
      - VITE_BE=${NGINX_DOMAIN}
      - VITE_CLIENT_ID=${CLIENT_ID}
      - VITE_FF_ENVIRONMENT=${FLAGSMITH_ENVIRONMENT}

  # Node.js Server App
  entry-server:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npx nx run entry-server:serve --host=0.0.0.0
    ports:
      - ${SERVER_PORT}:3000
    environment:
      - PORT=3000
      - DB_URI=${DB_URI}
      - REDIRECT_URL=${NGINX_DOMAIN}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - LOGS_REDIRECT_URL=${LOGS_REDIRECT_URL}
      - LOGS_CLIENT_ID=${LOGS_CLIENT_ID}
      - LOGS_CLIENT_SECRET=${LOGS_CLIENT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - NOTION_API_KEY=${NOTION_API_KEY}

  logs-app:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npx nx run logs-app:serve --host=0.0.0.0
    ports:
      - ${LOGS_PORT}:4200
    environment:
      - VITE_BE=${NGINX_DOMAIN}
      - VITE_CLIENT_ID=${LOGS_CLIENT_ID}

volumes:
  mono-node-modules: null
