version: '3'

services:
  # React App
  insights-app:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npx nx run insights-app:serve --host=0.0.0.0
    ports:
      - 4201:4200

  # Express App
  node-server:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npx nx run node-server:serve --host=0.0.0.0
    ports:
      - 4202:3000 # API Entry port

volumes:
  mono-node-modules: null
