version: '3'

services:
  nx-app-base:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile_local
    environment:
      - NODE_OPTIONS=--no-deprecation
    volumes:
      - ./:/app
      - mono-node-modules:/app/node_modules
